# Generated by Django 4.1 on 2022-08-11 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('intro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('total_step', models.IntegerField(max_length=1)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruits', to='app.club')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='app.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('submit_at', models.DateTimeField(auto_now=True)),
                ('temp_save', models.BooleanField(default=False)),
                ('curr_step', models.IntegerField(default=1)),
                ('applier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applies', to=settings.AUTH_USER_MODEL)),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliers', to='app.recruit')),
            ],
        ),
    ]
