# Generated by Django 4.1 on 2022-08-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_applyform_club_alter_comment_apply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
    ]
